version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: auction_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 221106
      POSTGRES_DB: auction_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: