<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AuctionPlatform.Domain\AuctionPlatform.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="MediatR" Version="14.1.0" />
      <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.11" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Bids\Queries\GetAllBIds\**" />
      <Compile Include="Bids\Queries\GetAllBids\BidDto.cs" />
      <Compile Include="Bids\Queries\GetAllBids\GetAllBidsQuery.cs" />
      <Compile Include="Bids\Queries\GetAllBids\GetAllBidsQueryHandler.cs" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="Bids\Queries\GetAllBIds\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Bids\Queries\GetAllBIds\**" />
    </ItemGroup>

</Project>
